

const productsData = [
    {
      id: 1,
      name: "Laptop & Desktop",
      category: "laptops",
      processor: "Intel Core i7",
      model: "Professional",
      ssd: "512 GB",
      price: 75000,
      imageUrl: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RW1geGv?ver=e834&q=90&m=6&h=705&w=1253&b=%23FFFFFFFF&f=jpg&o=f&p=140&aim=true",
    },
    {
      id: 2,
      name: "TV & Monitors",
      category: "tv-monitors",
      processor: "4K UHD",
      model: "Smart",
      ssd: "N/A",
      price: 55000,
      imageUrl: "https://www.lg.com/content/dam/channel/wcms/in/monitors/my-view-smart-monitor/mnt-smart-27sr50f-2023/gallery/02-gallery/smart-27sr50f-gallery-02-2010.jpg/_jcr_content/renditions/thum-1600x1062.jpeg",
    },
    {
      id: 2,
      name: "TV & Monitors",
      category: "tv-monitors",
      processor: "4K UHD",
      model: "pro",
      ssd: "N/A",
      price: 65000,
      imageUrl: "https://sathya.in/media/91677/catalog/LLOYD%20LED%2032HS550%20HD%20SMART.jpg",
    },
    {
      id: 2,
      name: "TV & Monitors",
      category: "tv-monitors",
      processor: "4K UHD",
      model: "Smart",
      ssd: "N/A",
      price: 75000,
      imageUrl: "https://sathya.in/media/91677/catalog/LLOYD%20LED%2032HS550%20HD%20SMART.jpg",
    },
    {
      id: 2,
      name: "TV & Monitors",
      category: "tv-monitors",
      processor: "4K UHD",
      model: "Smart",
      ssd: "N/A",
      price: 65000,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSngK7740GBwX5EVH8reAgIk02UfkurlU_qBvIjkvWhqhTUCpHghfVcpO6CtqoPyC_c5tg&usqp=CAU",
    },
    
    {
      id: 3,
      name: "Air Purifier / Cooler",
      category: "air-purifiers",
      processor: "HEPA Filter",
      model: "Advanced",
      ssd: "N/A",
      price: 25000,
      imageUrl: "https://images-cdn.ubuy.co.in/633ff7777688434a910f66fa-wiracil-probreezer-air-cooler-usb-cable.jpg",
    },
    {
      id: 3,
      name: "Air Purifier / Cooler",
      category: "air-purifiers",
      processor: "HEPA Filter",
      model: "Advanced",
      ssd: "N/A",
      price: 35000,
      imageUrl: "https://images-cdn.ubuy.co.in/633ff7777688434a910f66fa-wiracil-probreezer-air-cooler-usb-cable.jpg",
    },
    {
      id: 3,
      name: "Air Purifier / Cooler",
      category: "air-purifiers",
      processor: "HEPA Filter",
      model: "Advanced",
      ssd: "N/A",
      price: 45000,
      imageUrl: "https://images-cdn.ubuy.co.in/633ff7777688434a910f66fa-wiracil-probreezer-air-cooler-usb-cable.jpg",
    },
    {
      id: 3,
      name: "Air Purifier / Cooler",
      category: "air-purifiers",
      processor: "HEPA Filter",
      model: "Advanced",
      ssd: "N/A",
      price: 55000,
      imageUrl: "https://images-cdn.ubuy.co.in/633ff7777688434a910f66fa-wiracil-probreezer-air-cooler-usb-cable.jpg",
    },
    
    {
      id: 4,
      name: "Projector",
      category: "projectors",
      processor: "1080p HD",
      model: "Home Theater",
      ssd: "N/A",
      price: 35000,
      imageUrl: "https://images-cdn.ubuy.co.in/667f79fb498eb128a4199ebc-mini-projector-clokowe-2024-upgraded.jpg",
    },
    {
      id: 4,
      name: "Projector",
      category: "projectors",
      processor: "1080p HD",
      model: "Home Theater",
      ssd: "N/A",
      price: 55000,
      imageUrl: "https://m.media-amazon.com/images/I/61yEHU+9kqL.jpg",
    },
    {
      id: 4,
      name: "Projector",
      category: "projectors",
      processor: "1080p HD",
      model: "Home Theater",
      ssd: "N/A",
      price: 65000,
      imageUrl: "https://shop.zebronics.com/cdn/shop/files/Zeb-pixaplay58-pic1_eeb0a29f-910d-4349-90c8-4f741497bb4f.jpg?v=1718707795&width=2000",
    },
    {
      id: 4,
      name: "Projector",
      category: "projectors",
      processor: "1080p HD",
      model: "Home Theater",
      ssd: "N/A",
      price: 75000,
      imageUrl: "https://shop.zebronics.com/cdn/shop/files/zeb-pixaplay-55-pic1_c294dfd9-64d3-4ca7-bc37-84abd68dfcee.jpg?v=1718707751&width=2000",
    },
    

    {
      id: 5,
      name: "PlayStation 5",
      category: "ps5",
      processor: "AMD Ryzen Custom",
      model: "Gaming Console",
      ssd: "825 GB",
      price: 70000,
      imageUrl: "https://www.ubuy.com.eg/productimg/?image=aHR0cHM6Ly9pbWFnZXMtY2RuLnVidXkuY29tLmVnLzY2NGJlZGVlNzQzMGFiNjVhNTA1MDQ5NC1wczUtc2xpbS1jb25zb2xlLW1hcnZlbHMtc3BpZGVyLW1hbi0yLmpwZw.jpg",
    },
    {
      id: 5,
      name: "PlayStation 5",
      category: "ps5",
      processor: "AMD Ryzen Custom",
      model: "Gaming Console",
      ssd: "825 GB",
      price: 60000,
      imageUrl: "https://www.ubuy.com.eg/productimg/?image=aHR0cHM6Ly9pbWFnZXMtY2RuLnVidXkuY29tLmVnLzY2NGJlZGVlNzQzMGFiNjVhNTA1MDQ5NC1wczUtc2xpbS1jb25zb2xlLW1hcnZlbHMtc3BpZGVyLW1hbi0yLmpwZw.jpg",
    },
    {
      id: 5,
      name: "PlayStation 5",
      category: "ps5",
      processor: "AMD Ryzen Custom",
      model: "Gaming Console",
      ssd: "825 GB",
      price: 80000,
      imageUrl: "https://www.ubuy.com.eg/productimg/?image=aHR0cHM6Ly9pbWFnZXMtY2RuLnVidXkuY29tLmVnLzY2NGJlZGVlNzQzMGFiNjVhNTA1MDQ5NC1wczUtc2xpbS1jb25zb2xlLW1hcnZlbHMtc3BpZGVyLW1hbi0yLmpwZw.jpg",
    },
    {
      id: 5,
      name: "PlayStation 5",
      category: "ps5",
      processor: "AMD Ryzen Custom",
      model: "Gaming Console",
      ssd: "825 GB",
      price: 80000,
      imageUrl: "https://www.ubuy.com.eg/productimg/?image=aHR0cHM6Ly9pbWFnZXMtY2RuLnVidXkuY29tLmVnLzY2NGJlZGVlNzQzMGFiNjVhNTA1MDQ5NC1wczUtc2xpbS1jb25zb2xlLW1hcnZlbHMtc3BpZGVyLW1hbi0yLmpwZw.jpg",
    },
    
    {
      id: 6,
      name: "Tablet",
      category: "tablets",
      processor: "Apple M1",
      model: "Pro",
      ssd: "256 GB",
      price: 85000,
      imageUrl: "https://static.independent.co.uk/2024/11/01/16/best-tablets-1-november-2024.jpg?width=1200",
    },
    {
      id: 6,
      name: "Tablet",
      category: "tablets",
      processor: "Apple M1",
      model: "Pro",
      ssd: "256 GB",
      price: 85000,
      imageUrl: "https://static.independent.co.uk/2024/11/01/16/best-tablets-1-november-2024.jpg?width=1200",
    },
    {
      id: 6,
      name: "Tablet",
      category: "tablets",
      processor: "Apple M1",
      model: "Pro",
      ssd: "256 GB",
      price: 95000,
      imageUrl: "https://static.independent.co.uk/2024/11/01/16/best-tablets-1-november-2024.jpg?width=1200",
    },
    {
      id: 6,
      name: "Tablet",
      category: "tablets",
      processor: "Apple M1",
      model: "Pro",
      ssd: "256 GB",
      price: 95000,
      imageUrl: "https://static.independent.co.uk/2024/11/01/16/best-tablets-1-november-2024.jpg?width=1200",
    },
    
    {
      id: 7,
      name: "Printer & Scanner",
      category: "printers",
      processor: "LaserJet",
      model: "Office",
      ssd: "N/A",
      price: 20000,
      imageUrl: "https://i.dell.com/is/image/DellContent/content/dam/ss2/page-specific/category-pages/prod-2354-printer-epson-wf-c4810-lf-800x620.png?fmt=png-alpha&wid=800&hei=620",
    },
    {
      id: 7,
      name: "Printer & Scanner",
      category: "printers",
      processor: "LaserJet",
      model: "Office",
      ssd: "N/A",
      price: 20000,
      imageUrl: "https://i.dell.com/is/image/DellContent/content/dam/ss2/page-specific/category-pages/prod-2354-printer-epson-wf-c4810-lf-800x620.png?fmt=png-alpha&wid=800&hei=620",
    },
    {
      id: 7,
      name: "Printer & Scanner",
      category: "printers",
      processor: "LaserJet",
      model: "Office",
      ssd: "N/A",
      price: 30000,
      imageUrl: "https://i.dell.com/is/image/DellContent/content/dam/ss2/page-specific/category-pages/prod-2354-printer-epson-wf-c4810-lf-800x620.png?fmt=png-alpha&wid=800&hei=620",
    },
    {
      id: 7,
      name: "Printer & Scanner",
      category: "printers",
      processor: "LaserJet",
      model: "Office",
      ssd: "N/A",
      price: 30000,
      imageUrl: "https://i.dell.com/is/image/DellContent/content/dam/ss2/page-specific/category-pages/prod-2354-printer-epson-wf-c4810-lf-800x620.png?fmt=png-alpha&wid=800&hei=620",
    },
    

    {
      id: 8,
      name: "Audio & Karaoke",
      category: "audio",
      processor: "Wireless",
      model: "Studio",
      ssd: "N/A",
      price: 60000,
      imageUrl: "https://m.media-amazon.com/images/I/41YOD66S1BL.jpg",
    },
    {
      id: 8,
      name: "Audio & Karaoke",
      category: "audio",
      processor: "Wireless",
      model: "Studio",
      ssd: "N/A",
      price: 10000,
      imageUrl: "https://m.media-amazon.com/images/I/41YOD66S1BL.jpg",
    },
    {
      id: 8,
      name: "Audio & Karaoke",
      category: "audio",
      processor: "Wireless",
      model: "Studio",
      ssd: "N/A",
      price: 10000,
      imageUrl: "https://m.media-amazon.com/images/I/41YOD66S1BL.jpg",
    },
    {
      id: 8,
      name: "Audio & Karaoke",
      category: "audio",
      processor: "Wireless",
      model: "Studio",
      ssd: "N/A",
      price: 70000,
      imageUrl: "https://m.media-amazon.com/images/I/41YOD66S1BL.jpg",
    },
    
    {
      id: 9,
      name: "Kitchen Products",
      category: "kitchen",
      processor: "Smart Cooking",
      model: "Multi-Function",
      ssd: "N/A",
      price: 6000,
      imageUrl: "https://oggnhome.com/cdn/shop/articles/DALL_E_2024-12-18_18.44.57_-_A_collection_of_mango_wooden_kitchen_accessories_displayed_on_a_rustic_wooden_table._The_image_includes_beautifully_crafted_wooden_chopping_boards_wo_3f6c0404-bbf1-416b-948c-c4ff5ef56703.webp?v=1734528054",
    },
    {
      id: 9,
      name: "Kitchen Products",
      category: "kitchen",
      processor: "Smart Cooking",
      model: "Multi-Function",
      ssd: "N/A",
      price: 8000,
      imageUrl: "https://oggnhome.com/cdn/shop/articles/DALL_E_2024-12-18_18.44.57_-_A_collection_of_mango_wooden_kitchen_accessories_displayed_on_a_rustic_wooden_table._The_image_includes_beautifully_crafted_wooden_chopping_boards_wo_3f6c0404-bbf1-416b-948c-c4ff5ef56703.webp?v=1734528054",
    },
    {
      id: 9,
      name: "Kitchen Products",
      category: "kitchen",
      processor: "Smart Cooking",
      model: "Multi-Function",
      ssd: "N/A",
      price: 8000,
      imageUrl: "https://oggnhome.com/cdn/shop/articles/DALL_E_2024-12-18_18.44.57_-_A_collection_of_mango_wooden_kitchen_accessories_displayed_on_a_rustic_wooden_table._The_image_includes_beautifully_crafted_wooden_chopping_boards_wo_3f6c0404-bbf1-416b-948c-c4ff5ef56703.webp?v=1734528054",
    },
    {
      id: 9,
      name: "Kitchen Products",
      category: "kitchen",
      processor: "Smart Cooking",
      model: "Multi-Function",
      ssd: "N/A",
      price: 6000,
      imageUrl: "https://oggnhome.com/cdn/shop/articles/DALL_E_2024-12-18_18.44.57_-_A_collection_of_mango_wooden_kitchen_accessories_displayed_on_a_rustic_wooden_table._The_image_includes_beautifully_crafted_wooden_chopping_boards_wo_3f6c0404-bbf1-416b-948c-c4ff5ef56703.webp?v=1734528054",
    },
    
    {
      id: 10,
      name: "Video Conference",
      category: "video-conference",
      processor: "HD Webcam",
      model: "Business",
      ssd: "N/A",
      price: 11000,
      imageUrl: "https://res.cloudinary.com/dthpnue1d/image/upload/v1739355579/How_Much_Does_it_Cost_to_Build_a_Video_Conferencing_App_like_Zoom_8ba1ed8d09.webp",
    },
    {
      id: 10,
      name: "Video Conference",
      category: "video-conference",
      processor: "HD Webcam",
      model: "Business",
      ssd: "N/A",
      price: 11000,
      imageUrl: "https://res.cloudinary.com/dthpnue1d/image/upload/v1739355579/How_Much_Does_it_Cost_to_Build_a_Video_Conferencing_App_like_Zoom_8ba1ed8d09.webp",
    },
    {
      id: 10,
      name: "Video Conference",
      category: "video-conference",
      processor: "HD Webcam",
      model: "Business",
      ssd: "N/A",
      price: 16000,
      imageUrl: "https://res.cloudinary.com/dthpnue1d/image/upload/v1739355579/How_Much_Does_it_Cost_to_Build_a_Video_Conferencing_App_like_Zoom_8ba1ed8d09.webp",
    },
    {
      id: 10,
      name: "Video Conference",
      category: "video-conference",
      processor: "HD Webcam",
      model: "Business",
      ssd: "N/A",
      price: 16000,
      imageUrl: "https://res.cloudinary.com/dthpnue1d/image/upload/v1739355579/How_Much_Does_it_Cost_to_Build_a_Video_Conferencing_App_like_Zoom_8ba1ed8d09.webp",
    },
    

    {
      id: 11,
      name: "Office Equipments",
      category: "office",
      processor: "Multi-purpose",
      model: "Standard",
      ssd: "N/A",
      price: 18000,
      imageUrl: "https://img.freepik.com/free-vector/office-attributes-illustration-set_74855-306.jpg",
    },
    {
      id: 11,
      name: "Office Equipments",
      category: "office",
      processor: "Multi-purpose",
      model: "Standard",
      ssd: "N/A",
      price: 18000,
      imageUrl: "https://img.freepik.com/free-vector/office-attributes-illustration-set_74855-306.jpg",
    },
    {
      id: 11,
      name: "Office Equipments",
      category: "office",
      processor: "Multi-purpose",
      model: "Standard",
      ssd: "N/A",
      price: 18000,
      imageUrl: "https://img.freepik.com/free-vector/office-attributes-illustration-set_74855-306.jpg",
    },
    {
      id: 11,
      name: "Office Equipments",
      category: "office",
      processor: "Multi-purpose",
      model: "Standard",
      ssd: "N/A",
      price: 20000,
      imageUrl: "https://img.freepik.com/free-vector/office-attributes-illustration-set_74855-306.jpg",
    },
    
    {
      id: 12,
      name: "Security Cameras",
      category: "security",
      processor: "Night Vision",
      model: "Surveillance",
      ssd: "N/A",
      price: 25000,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIx9eYo9tP30UgifxEVkrmte0V2IEc-LR9Nw&s",
    },
    {
      id: 12,
      name: "Security Cameras",
      category: "security",
      processor: "Night Vision",
      model: "Surveillance",
      ssd: "N/A",
      price: 25000,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIx9eYo9tP30UgifxEVkrmte0V2IEc-LR9Nw&s",
    },
    {
      id: 12,
      name: "Security Cameras",
      category: "security",
      processor: "Night Vision",
      model: "Surveillance",
      ssd: "N/A",
      price: 30000,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIx9eYo9tP30UgifxEVkrmte0V2IEc-LR9Nw&s",
    },
    {
      id: 12,
      name: "Security Cameras",
      category: "security",
      processor: "Night Vision",
      model: "Surveillance",
      ssd: "N/A",
      price: 25000,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIx9eYo9tP30UgifxEVkrmte0V2IEc-LR9Nw&s",
    },
    
    {
      id: 1,
      name: "Gaming Laptop",
      category: "laptops",
      processor: "Intel Core i9",
      model: "Ultra",
      ssd: "1 TB",
      price: 120000,
      imageUrl: "https://i.redd.it/msl53vqmf4xb1.jpg",
    },
    {
      id: 1,
      name: "Business Laptop",
      category: "laptops",
      processor: "AMD Ryzen 7",
      model: "Pro",
      ssd: "512 GB",
      price: 95000,
      imageUrl: "https://cdn.thewirecutter.com/wp-content/media/2024/07/businesslaptops-2048px-233284-2x1-1.jpg?width=2048&quality=75&crop=2:1&auto=webp",
    },
    {
      id: 1,
      name: "Student Laptop",
      category: "laptops",
      processor: "Intel Core i5",
      model: "Basic",
      ssd: "256 GB",
      price: 50000,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT2vldUSyJG9qO4Hf0O8RMYZjbk7leQZgygA&s",
    },
    {
      id: 1,
      name: "MacBook Pro",
      category: "laptops",
      processor: "Apple M2",
      model: "Premium",
      ssd: "512 GB",
      price: 140000,
      imageUrl: "https://i.ytimg.com/vi/zqJ9A6N-YB4/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCgYGEY4vhd5RjA5HCvv75fQxXRhQ",
    },
    {
      id: 1,
      name: "Budget Laptop",
      category: "laptops",
      processor: "Intel Pentium",
      model: "Entry-Level",
      ssd: "128 GB",
      price: 30000,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8mBqn6Vu5E7aFwNAANmxKZwgrbt39v02OyA&s",
    },
    {
      id: 1,
      name: "Convertible Laptop",
      category: "laptops",
      processor: "Intel Core i5",
      model: "2-in-1",
      ssd: "512 GB",
      price: 70000,
      imageUrl: "https://img.etimg.com/thumb/width-1200,height-1200,imgsize-111423,resizemode-75,msid-68090963/magazines/panache/lenovo-yoga-c930-glass-review-conventional-convertible-laptop-with-a-premium-design.jpg",
    },
    {
      id: 1,
      name: "Workstation Laptop",
      category: "laptops",
      processor: "Intel Xeon",
      model: "Powerhouse",
      ssd: "2 TB",
      price: 180000,
      imageUrl: "https://cdn.trendhunterstatic.com/thumbs/530/lt1-laptop-concept.jpeg?auto=webp",
    },
    

  ];

  export default productsData;




  
